trigger:
- master

pool:
  vmImage: 'macOs-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test
  displayName: 'npm install and test'

schedule:
    - cron: "30 06 * * *"
      displayName: Daily build
      branches:
        include:
          - master
