trigger:
- master

pool:
  vmImage: 'macOs-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test
  displayName: 'npm install and test'

schedules:
  - cron: "25 19 * * *"
    displayName: Daily build
    branches:
      include:
        - master
  - cron: "0 0 * * Sun"
    displayName: Weekly Sunday build
    branches:
      include:
        - master
    always: true