trigger:
- master

pool:
  vmImage: 'macOs-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test
  displayName: 'npm install and test'

schedules:
  - cron: "0 09 * * *"
    displayName: Daily build
    branches:
      include:
        - master
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - master
    always: true